/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsOverviewRouteImport } from './routes/results/overview'
import { Route as ResultsResultIDRouteImport } from './routes/results/$resultID'
import { Route as GamePlayingRouteImport } from './routes/game/playing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsOverviewRoute = ResultsOverviewRouteImport.update({
  id: '/results/overview',
  path: '/results/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsResultIDRoute = ResultsResultIDRouteImport.update({
  id: '/results/$resultID',
  path: '/results/$resultID',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayingRoute = GamePlayingRouteImport.update({
  id: '/game/playing',
  path: '/game/playing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/playing': typeof GamePlayingRoute
  '/results/$resultID': typeof ResultsResultIDRoute
  '/results/overview': typeof ResultsOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/playing': typeof GamePlayingRoute
  '/results/$resultID': typeof ResultsResultIDRoute
  '/results/overview': typeof ResultsOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/playing': typeof GamePlayingRoute
  '/results/$resultID': typeof ResultsResultIDRoute
  '/results/overview': typeof ResultsOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/playing' | '/results/$resultID' | '/results/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/playing' | '/results/$resultID' | '/results/overview'
  id:
    | '__root__'
    | '/'
    | '/game/playing'
    | '/results/$resultID'
    | '/results/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamePlayingRoute: typeof GamePlayingRoute
  ResultsResultIDRoute: typeof ResultsResultIDRoute
  ResultsOverviewRoute: typeof ResultsOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/overview': {
      id: '/results/overview'
      path: '/results/overview'
      fullPath: '/results/overview'
      preLoaderRoute: typeof ResultsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$resultID': {
      id: '/results/$resultID'
      path: '/results/$resultID'
      fullPath: '/results/$resultID'
      preLoaderRoute: typeof ResultsResultIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/playing': {
      id: '/game/playing'
      path: '/game/playing'
      fullPath: '/game/playing'
      preLoaderRoute: typeof GamePlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamePlayingRoute: GamePlayingRoute,
  ResultsResultIDRoute: ResultsResultIDRoute,
  ResultsOverviewRoute: ResultsOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
